# Site settings
title: Notes from Ranjan
email: ranjan.bagchi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Minor musings and frontend hacks.  Which are amusing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rbagchi.github.io" # the base hostname & protocol for your site
twitter_username: rbagchi
github_username:  rbagchi

# Build settings
encoding:     "utf-8"
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
kramdown:
  input: GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
